const K="kkm-demo";let d=JSON.parse(localStorage.getItem(K)||"null")||{user:null,items:[
{id:"1",c:"raw",n:"KK Beef Floss - Original",u:"Gram",q:2000,b:[["2026-08-28",1000],["2026-10-30",1000]]},
{id:"2",c:"raw",n:"KK Syrup Strawberry",u:"ml",q:12000,b:[["2026-08-29",2000],["2026-09-20",10000]]},
{id:"3",c:"raw",n:"KK Fresh Milk",u:"ml",q:3500,b:[["2026-09-05",3500]]},
{id:"4",c:"kitchen",n:"KK Cocktail Napkin",u:"Pac",q:21},{id:"5",c:"kitchen",n:"KK Black Straw Plastic",u:"Pac",q:37},
{id:"6",c:"merch",n:"KK Core Merch Press Cup",display:"Hustle Black Cup",u:"PCS",q:12,p:139000},
{id:"7",c:"merch",n:"KK Core Merch Sip Tumbler",display:"Breezy Mint Tumbler",u:"PCS",q:4,p:199000}],tx:[],so:[],opening:[],sales:[],orders:[]};
const users={admin:["Admin","ADMIN"],manager:["Manager","MANAGER"],staff:["Barista","STAFF"],viewer:["Viewer","VIEWER"]};
const $=x=>document.getElementById(x), save=()=>localStorage.setItem(K,JSON.stringify(d));
const money=n=>"Rp "+(+n||0).toLocaleString("id-ID"), date=s=>new Date(s+"T00:00:00").toLocaleDateString("id-ID",{day:"2-digit",month:"short",year:"numeric"});
function days(s){return Math.ceil((new Date(s)-new Date(new Date().toDateString()))/86400000)}
function login(){ $("app").innerHTML=`<main style="min-height:100vh;display:grid;place-items:center;padding:20px"><form id="f" class="card" style="width:min(420px,100%);padding:28px"><img src="assets/logo-so.png" style="width:64px"><h1>KKMongin</h1><div class="small">Inventory operasional outlet</div><div class="field"><label>Username</label><input id="un" required></div><div class="field"><label>Password</label><input id="pw" type="password" required></div><button class="btn primary" style="width:100%">Masuk</button><p class="small">Demo development: admin/admin · manager/manager · staff/staff · viewer/viewer</p></form></main>`;$("f").onsubmit=e=>{e.preventDefault();if(!users[un.value]||pw.value!==un.value)return alert("Username/password salah");d.user={u:un.value,name:users[un.value][0],role:users[un.value][1]};save();render()}}
function allowed(x){let r=d.user.role;return r==="ADMIN"||r==="MANAGER"&&x!=="admin"||r==="STAFF"&&["dashboard","out","in","so","inventory"].includes(x)||r==="VIEWER"&&["dashboard","so","inventory"].includes(x)}
function shell(){ $("app").innerHTML=`<main class="app"><div class="top"><div><div class="small">Hi ${d.user.name} · ${d.user.role}</div><div id="pt" class="title">Dashboard</div></div><button class="btn soft" id="lo">Keluar</button></div><nav class="nav">${["dashboard","out","in","so","opening","estimate","sales"].filter(allowed).map((x,i)=>`<button data-p="${x}">${x==="so"?'<img src="assets/logo-so.png">':["⌂","↓","↑","◫","▣","◌"][i]||"•"}<br>${x==="dashboard"?"Dashboard":x==="so"?"Daily SO":x==="opening"?"Stock Awal":x==="estimate"?"Estimasi":x==="sales"?"Manager":x.toUpperCase()}</button>`).join("")}</nav><div id="pages"></div></main><div id="modal" class="modal"><div id="sheet" class="sheet"></div></div>`;$("lo").onclick=()=>{d.user=null;save();login()};document.querySelectorAll("[data-p]").forEach(b=>b.onclick=()=>show(b.dataset.p));show("dashboard")}
function raw(){return d.items.filter(i=>i.c==="raw")}function alerts(){return raw().flatMap(i=>(i.b||[]).map(b=>({...b,i}))).filter(x=>days(x[0])<=50).sort((a,b)=>new Date(a[0])-new Date(b[0]))}
function card(i){if(i.c==="raw")return `<div class="card raw"><div><div class="name">${i.n}</div><div class="stock">${i.q.toLocaleString("id-ID")} ${i.u}</div>${(i.b||[]).sort((a,b)=>new Date(a[0])-new Date(b[0])).map(b=>`<div class="exp ${days(b[0])<0?"expired":days(b[0])<=50?"soon":""}">Exp ${date(b[0])} · ${b[1].toLocaleString("id-ID")} ${i.u}</div>`).join("")}</div><div class="small">Stock<br><b>${i.q?"Available":"Habis"}</b></div></div>`;return `<div class="card merch"><div class="pic">${i.c==="merch"?"☕":"▤"}</div><div><div class="name">${i.display||i.n}</div>${i.c==="merch"?`<div class="price">${money(i.p)}</div>`:""}</div><div class="qty">${i.q}<br><span class="small">${i.u}</span></div></div>`}
function dashboard(){let a=alerts();return `<div class="sec">PERHATIAN · RAW MATERIAL</div>${a.length?a.map(x=>`<div class="card alert"><b>${x.i.n}</b><div class="small">${days(x[0])<0?"EXPIRED":`Exp ${date(x[0])} · ${days(x[0])} hari lagi`} · ${x[1]} ${x.i.u}</div></div>`).join(""):`<div class="card small">Tidak ada expiry ≤ 50 hari.</div>`}<div class="sec">RAW MATERIAL</div><div class="rawgrid">${raw().map(card).join("")}</div><div class="sec">KITCHEN SUPPLIER</div>${d.items.filter(i=>i.c==="kitchen").map(card).join("")}<div class="sec">MERCHANDISE</div>${d.items.filter(i=>i.c==="merch").map(card).join("")}`}
function show(p){$("pt").textContent=p==="dashboard"?"Dashboard":p==="so"?"Daily SO":p==="in"?"Barang Masuk (IN)":p==="out"?"Barang Keluar (OUT)":p==="opening"?"Stock Awal":p==="estimate"?"Estimasi Pengorderan":p==="sales"?"Data Penjualan 30 Hari":"Inventory";$("pages").innerHTML=p==="dashboard"?dashboard():p==="so"?so():p==="in"?inPage():p==="out"?outPage():p==="opening"?opening():p==="estimate"?estimate():p==="sales"?sales():inventory();document.querySelectorAll("[data-p]").forEach(b=>b.classList.toggle("active",b.dataset.p===p))}
function modal(title,html){$("sheet").innerHTML=`<button class="close" onclick="closeM()">×</button><h3>${title}</h3>${html}`;$("modal").classList.add("show")}function closeM(){$("modal").classList.remove("show")}
function inPage(){return `<div class="toolbar"><button class="btn primary" onclick="openIn()">+ Barang Masuk</button><button class="btn soft" onclick="newItem()">+ Barang Baru</button></div><div class="sec">HISTORY IN</div><div class="wrap"><table class="table"><tr><th>Tanggal</th><th>Item</th><th>Qty</th><th>Exp</th></tr>${d.tx.filter(x=>x.t==="IN").map(x=>`<tr><td>${date(x.date)}</td><td>${x.n}</td><td>${x.q} ${x.u}</td><td>${x.e?date(x.e):"-"}</td></tr>`).join("")}</table></div>`}
function outPage(){return `<div class="notice">OUT = backroom → bar. Merchandise = terjual. Kitchen Supplier = terpakai. Raw Material mengikuti FEFO.</div><button class="btn primary" style="margin-top:10px" onclick="openOut()">+ Catat OUT</button><div class="sec">HISTORY OUT</div><div class="wrap"><table class="table"><tr><th>Item</th><th>Qty</th><th>Detail</th></tr>${d.tx.filter(x=>x.t==="OUT").map(x=>`<tr><td>${x.n}</td><td>-${x.q} ${x.u}</td><td>${x.detail}</td></tr>`).join("")}</table></div>`}
function so(){return `<div class="notice">Daily SO hanya raw material yang ada di bar. Hasil SO menjadi acuan stok akhir dan Estimasi Pengorderan PIC.</div><button class="btn primary" style="margin-top:10px" onclick="openSO()">+ Input Daily SO</button><div class="sec">SO TERAKHIR</div>${d.so.slice(-8).reverse().map(x=>`<div class="card"><b>${x.n}</b><div class="small">System ${x.sys} ${x.u} · Physical <b>${x.phys} ${x.u}</b> · Selisih ${x.diff} ${x.u}</div></div>`).join("")}`}
function opening(){return `<div class="notice">Untuk inventory ulang backroom. Gunakan tombol hapus semua saat baseline baru dimulai.</div><button class="btn primary" style="margin:10px 6px 10px 0" onclick="openOpening()">+ Stock Awal</button><button class="btn soft" onclick="clearOpening()">Hapus semua</button><div class="sec">DATA</div>${d.opening.map(x=>`<div class="card">${x.n} · ${x.q} ${x.u} · ${date(x.date)}</div>`).join("")}`}
function estimate(){return `<div class="notice">Estimasi membaca stok akhir + penjualan 30 hari + buffer. PIC mengatur tanggal delivery/kedatangan dan UOM order.</div><div class="sec">REKOMENDASI ORDER</div>${raw().map(i=>{let s=d.sales.find(x=>x.id===i.id),avg=(s?.q||0)/30,need=Math.max(0,Math.ceil(avg*(1+(s?.buf||0)/100)*7-i.q));return `<div class="card"><div class="name">${i.n}</div><div class="small">Stock ${i.q} ${i.u} · Sales 30 hari ${s?.q||0} · Buffer ${s?.buf||0}% · UOM order ${s?.ou||"-"}</div><div class="stock">Order ${need.toLocaleString("id-ID")} ${i.u}</div></div>`}).join("")}`}
function sales(){return `<button class="btn primary" onclick="openSales()">+ Data Penjualan 30 Hari</button><div class="sec">DATA</div>${raw().map(i=>{let s=d.sales.find(x=>x.id===i.id);return `<div class="card"><b>${i.n}</b><div class="small">${s?.q||0} ${i.u} · ${s?.ou||"—"} · Buffer ${s?.buf||0}%</div></div>`}).join("")}`}
function inventory(){return `<div class="toolbar"><input id="search" placeholder="Cari item..."></div><div id="list">${d.items.map(card).join("")}</div>`}
function opts(){return d.items.map(i=>`<option value="${i.id}">${i.display||i.n} — ${i.u}</option>`).join("")}
function openIn(){modal("Barang Masuk (IN)",`<div class="field"><label>Item</label><select id="ii">${opts()}</select></div><div class="grid2"><div class="field"><label>Qty</label><input id="iq" type="number" step="any"></div><div class="field"><label>UOM</label><input id="iu"></div><div class="field"><label>Expiry</label><input id="ie" type="date"></div><div class="field"><label>Batch</label><input id="ib"></div></div><button class="btn primary" onclick="doIn()">Simpan IN</button>`);$("ii").onchange=()=>iu.value=d.items.find(i=>i.id===ii.value).u;$("ii").onchange()}
function doIn(){let i=d.items.find(x=>x.id===ii.value),q=+iq.value;if(iu.value.toLowerCase()!==i.u.toLowerCase())return alert("UOM tidak sesuai");i.q+=q;if(i.c==="raw"&&ie.value){i.b=i.b||[];i.b.push([ie.value,q])}d.tx.push({t:"IN",n:i.n,q,u:i.u,e:ie.value,date:new Date().toISOString().slice(0,10)});save();closeM();show("in")}
function openOut(){modal("Barang Keluar (OUT)",`<div class="field"><label>Cari / pilih item</label><select id="oi">${opts()}</select></div><div class="field"><label>Qty</label><input id="oq" type="number" step="any"></div><div class="field"><label>UOM</label><input id="ou"></div><div id="fb" class="notice"></div><button class="btn primary" onclick="doOut()">Simpan OUT</button>`);$("oi").onchange=()=>{let i=d.items.find(x=>x.id===oi.value);ou.value=i.u;fb.innerHTML=i.c==="raw"?"Saran FEFO:<br>"+(i.b||[]).sort((a,b)=>new Date(a[0])-new Date(b[0])).map(x=>`Exp ${date(x[0])} · ${x[1]} ${i.u}`).join("<br>"):""}
$("oi").onchange()}
function doOut(){let i=d.items.find(x=>x.id===oi.value),q=+oq.value;if(ou.value.toLowerCase()!==i.u.toLowerCase())return alert("UOM tidak sesuai");if(q>i.q)return alert("Stock tidak cukup");i.q-=q;if(i.c==="raw"){let r=q;i.b.sort((a,b)=>new Date(a[0])-new Date(b[0]));for(let b of i.b){let x=Math.min(r,b[1]);b[1]-=x;r-=x;if(!r)break}i.b=i.b.filter(x=>x[1]>0)}d.tx.push({t:"OUT",n:i.n,q,u:i.u,detail:i.c==="merch"?"TERJUAL":i.c==="kitchen"?"TERPAKAI":"FEFO",date:new Date().toISOString().slice(0,10)});save();closeM();show("out")}
function openSO(){modal("Daily SO",`<div class="field"><label>Raw Material di Bar</label><select id="si">${raw().map(i=>`<option value="${i.id}">${i.n} — ${i.u}</option>`).join("")}</select></div><div class="field"><label>Physical / sisa di bar</label><input id="sq" type="number" step="any"></div><div class="field"><label>Note / Waste</label><textarea id="sn"></textarea></div><button class="btn primary" onclick="doSO()">Simpan SO</button>`)}
function doSO(){let i=d.items.find(x=>x.id===si.value),q=+sq.value;d.so.push({n:i.n,u:i.u,sys:i.q,phys:q,diff:q-i.q,date:new Date().toISOString().slice(0,10),note:sn.value});save();closeM();show("so")}
function openOpening(){modal("Stock Awal",`<div class="field"><label>Item</label><select id="opi">${opts()}</select></div><div class="field"><label>Qty</label><input id="opq" type="number" step="any"></div><button class="btn primary" onclick="doOpening()">Simpan</button>`)}
function doOpening(){let i=d.items.find(x=>x.id===opi.value);d.opening.push({n:i.n,q:+opq.value,u:i.u,date:new Date().toISOString().slice(0,10)});save();closeM();show("opening")}
function clearOpening(){if(confirm("Hapus semua Stock Awal?")){d.opening=[];save();show("opening")}}
function newItem(){modal("Tambah Barang Baru",`<div class="field"><label>Nama internal</label><input id="nn"></div><div class="field"><label>Nama display</label><input id="nd"></div><div class="grid2"><div class="field"><label>Kategori</label><select id="nc"><option value="raw">Raw Material</option><option value="kitchen">Kitchen Supplier</option><option value="merch">Merchandise</option></select></div><div class="field"><label>UOM</label><input id="nu"></div><div class="field"><label>Qty awal</label><input id="nq" type="number"></div><div class="field"><label>Harga display merchandise</label><input id="np" type="number"></div></div><button class="btn primary" onclick="doNew()">Tambah</button>`)}
function doNew(){d.items.push({id:Date.now()+"",c:nc.value,n:nn.value,display:nd.value,u:nu.value,q:+nq.value||0,p:+np.value||0,b:[]});save();closeM();show("in")}
function openSales(){modal("Penjualan 30 Hari",`<div class="field"><label>Raw Material</label><select id="sli">${raw().map(i=>`<option value="${i.id}">${i.n}</option>`).join("")}</select></div><div class="grid2"><div class="field"><label>Qty 30 hari</label><input id="slq" type="number"></div><div class="field"><label>UOM order</label><select id="slu"><option>Pac</option><option>Bottle</option><option>CTN</option></select></div><div class="field"><label>Buffer %</label><input id="slb" type="number" value="0"></div></div><button class="btn primary" onclick="doSales()">Simpan</button>`)}
function doSales(){let old=d.sales.find(x=>x.id===sli.value),v={id:sli.value,q:+slq.value,ou:slu.value,buf:+slb.value};if(old)Object.assign(old,v);else d.sales.push(v);save();closeM();show("sales")}
function render(){d.user? (shell()) : login()} render();