const KEY='inventoryKK_v3';
const SESSION='inventoryKK_session_v3';
const GROUPS={
  Admin:{label:'Admin',color:'brown',pages:['dashboard','master','warehouse','dailyso','estimate','settings'],actions:{create:true,edit:true,delete:true,manageUsers:true,reset:true,export:true,import:true}},
  Manager:{label:'Manager',color:'blue',pages:['dashboard','master','warehouse','dailyso','estimate','settings'],actions:{create:true,edit:true,delete:false,manageUsers:false,reset:false,export:true,import:true}},
  Staff:{label:'Staff',color:'green',pages:['dashboard','master','warehouse','dailyso','estimate'],actions:{create:true,edit:false,delete:false,manageUsers:false,reset:false,export:false,import:false}},
  Viewer:{label:'Viewer',color:'gray',pages:['dashboard','master','dailyso','estimate'],actions:{create:false,edit:false,delete:false,manageUsers:false,reset:false,export:false,import:false}}
};
const DEFAULT_USERS=[
 {id:'u-admin',username:'admin',name:'Administrator',password:'admin123',group:'Admin',active:true},
 {id:'u-manager',username:'manager',name:'Manager',password:'654321',group:'Manager',active:true},
 {id:'u-staff',username:'staff',name:'Staff Gudang',password:'123456',group:'Staff',active:true},
 {id:'u-viewer',username:'viewer',name:'Viewer',password:'111111',group:'Viewer',active:true}
];
const seedItems=[
 {id:'i-1',name:'Cup 16oz',sku:'CUP16',category:'Raw Material',uomBesar:'Karton',uomKecil:'Pcs',konversi:1000,opening:600,price:0,displayName:'Cup 16oz'},
 {id:'i-2',name:'Cup 22oz',sku:'CUP22',category:'Raw Material',uomBesar:'Karton',uomKecil:'Pcs',konversi:1000,opening:420,price:0,displayName:'Cup 22oz'},
 {id:'i-3',name:'Coffee Bean House Blend',sku:'COFHB',category:'Raw Material',uomBesar:'Bag',uomKecil:'Gram',konversi:1000,opening:8500,price:0,displayName:'House Blend'},
 {id:'i-4',name:'Syrup Vanilla',sku:'SYR-VAN',category:'Raw Material',uomBesar:'Botol',uomKecil:'Ml',konversi:750,opening:2400,price:0,displayName:'Vanilla'},
 {id:'i-5',name:'Tumbler KK',sku:'MERCH-TMB',category:'Merchandise',uomBesar:'Pack',uomKecil:'Pcs',konversi:20,opening:35,price:85000,displayName:'Tumbler KK'},
 {id:'i-6',name:'Paper Bag Large',sku:'PB-L',category:'Kitchen Supplier',uomBesar:'Pack',uomKecil:'Pcs',konversi:100,opening:280,price:0,displayName:'Paper Bag L'}
];
const today=()=>new Date().toISOString().slice(0,10);
const id=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
let state={users:[],items:[],transactions:[],batches:[],so:[],drafts:[],activity:[]};
let currentUser=null;
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
function load(){try{const raw=localStorage.getItem(KEY);if(raw){state=JSON.parse(raw)}else{state={users:DEFAULT_USERS,items:seedItems,transactions:[],batches:[],so:[],drafts:[],activity:[]};save();}}catch(e){state={users:DEFAULT_USERS,items:seedItems,transactions:[],batches:[],so:[],drafts:[],activity:[]};save();}}
function currentStock(itemId){const item=state.items.find(x=>x.id===itemId);let qty=Number(item?.opening||0);for(const t of state.transactions){if(t.itemId!==itemId)continue;qty += t.type==='IN'?Number(t.qty):Number(-t.qty)}return qty;}
function itemName(itemId){return state.items.find(x=>x.id===itemId)?.name||'Item dihapus';}
function formatQty(n){return new Intl.NumberFormat('id-ID',{maximumFractionDigits:2}).format(Number(n||0));}
function formatDateTime(v){try{return new Date(v).toLocaleString('id-ID',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}catch{return '-'}}
function logActivity(type,itemId,text){state.activity.unshift({id:id(),at:new Date().toISOString(),type,itemId,text,user:currentUser?.name||'System'});state.activity=state.activity.slice(0,50);save();}
function can(action){return !!(currentUser&&GROUPS[currentUser.group]?.actions?.[action]);}
function pageAllowed(page){return !!(currentUser&&GROUPS[currentUser.group]?.pages.includes(page));}
function showToast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>el.classList.remove('show'),2200)}
function openModal(title,body,submitText,submitFn){const root=$('#modalRoot');root.innerHTML=`<div class="modal-overlay" id="activeModal"><div class="modal"><div class="modal-head"><h3>${title}</h3><button class="close" type="button" id="closeModal">✕</button></div><div class="modal-body">${body}</div><div class="modal-actions"><button class="btn secondary" type="button" id="cancelModal">Batal</button><button class="btn primary" type="button" id="submitModal">${submitText}</button></div></div></div>`;$('#closeModal').onclick=closeModal;$('#cancelModal').onclick=closeModal;$('#submitModal').onclick=()=>submitFn(root);}
function closeModal(){$('#modalRoot').innerHTML=''}
function login(user,pass){const u=state.users.find(x=>x.username.toLowerCase()===user.toLowerCase()&&x.password===pass&&x.active);if(!u){$('#loginError').textContent='Username atau password salah.';return}currentUser={...u};localStorage.setItem(SESSION,JSON.stringify({id:u.id}));$('#loginError').textContent='';bootApp();}
function logout(){localStorage.removeItem(SESSION);currentUser=null;$('#appView').classList.add('hidden');$('#loginView').classList.remove('hidden');$('#loginPassword').value='';}
function restoreSession(){const s=JSON.parse(localStorage.getItem(SESSION)||'null');if(s){const u=state.users.find(x=>x.id===s.id&&x.active);if(u){currentUser={...u};bootApp();return}}$('#appView').classList.add('hidden');$('#loginView').classList.remove('hidden');}
function bootApp(){loadHeader();applyNavPermissions();showPage('dashboard');renderAll();}
function loadHeader(){$('#helloName').textContent=currentUser.name.split(' ')[0];$('#roleText')?.remove?.();$('#userLabel').textContent=currentUser.name;$('#userAvatar').textContent=currentUser.name[0].toUpperCase();$('#menuUserName').textContent=currentUser.name;$('#menuUserGroup').textContent='Group: '+currentUser.group;$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');}
function applyNavPermissions(){ $$('.nav-btn').forEach(b=>{const p=b.dataset.page;b.style.display=pageAllowed(p)?'flex':'none'}); if(!pageAllowed('settings'))$('#userMenuBtn').title=''; }
function showPage(page){if(!pageAllowed(page))return showToast('Akses halaman ditolak untuk group ini.');$$('.page').forEach(p=>p.classList.remove('active'));$(`#page-${page}`).classList.add('active');$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.page===page));const labels={dashboard:'Dashboard',master:'Master Item',warehouse:'Gudang',dailyso:'Daily SO',estimate:'Estimasi Order',settings:'Pengaturan'};$('#pageSubtitle').textContent=labels[page]||'';closeUserMenu();}
function closeUserMenu(){$('#userMenu').classList.add('hidden')}
function renderAll(){renderDashboard();renderMaster();renderWarehouse();renderSO();renderEstimate();renderSettings();}
function renderDashboard(){const low=state.items.filter(i=>currentStock(i.id)<5).sort((a,b)=>currentStock(a.id)-currentStock(b.id));const exp=state.batches.filter(b=>b.qty>0&&((new Date(b.expireDate)-new Date())/86400000)<=7&&new Date(b.expireDate)>=new Date()).sort((a,b)=>new Date(a.expireDate)-new Date(b.expireDate));const soToday=state.so.filter(s=>s.date===today());const soPct=state.items.length?Math.round(soToday.length/state.items.length*100):0;$('#metricItems').textContent=state.items.length;$('#metricLow').textContent=low.length;$('#metricExpire').textContent=exp.length;$('#metricSO').textContent=soPct+'%';
 $('#lowStockList').innerHTML=low.slice(0,5).map(i=>`<div class="row-card"><div class="row-top"><div><div class="row-title">${esc(i.name)}</div><div class="row-meta">${esc(i.sku||'-')} · ${esc(i.uomKecil)}</div></div><div class="stock-pill"><strong>${formatQty(currentStock(i.id))}</strong><small>stok</small></div></div></div>`).join('')||'<div class="list-empty">Stok aman 🎉</div>';
 $('#expiryList').innerHTML=exp.slice(0,5).map(b=>{const d=Math.ceil((new Date(b.expireDate)-new Date())/86400000);return `<div class="row-card"><div class="row-top"><div><div class="row-title">${esc(itemName(b.itemId))}</div><div class="row-meta">Expire ${esc(b.expireDate)} · Qty ${formatQty(b.qty)}</div></div><span class="badge ${d<=2?'danger':'warn'}">${d} hari</span></div></div>`}).join('')||'<div class="list-empty">Tidak ada batch yang akan expire.</div>';
 $('#activityList').innerHTML=state.activity.slice(0,10).map(a=>`<div class="row-card activity-row"><div class="activity-icon">${a.type==='IN'?'📥':a.type==='OUT'?'📤':a.type==='SO'?'🧾':a.type==='ITEM'?'📦':'⚙️'}</div><div><div class="activity-title">${esc(a.text)}</div><div class="activity-desc">${esc(a.user)} · ${formatDateTime(a.at)}</div></div><div class="activity-time">${esc(itemName(a.itemId))}</div></div>`).join('')||'<div class="list-empty">Belum ada aktivitas.</div>';}
function renderMaster(){const search=($('#masterSearch')?.value||'').toLowerCase();const cat=$('#masterCategory')?.value||'all';let arr=state.items.filter(i=>(cat==='all'||i.category===cat)&&(`${i.name} ${i.sku}`.toLowerCase().includes(search)));$('#masterList').innerHTML=arr.map(i=>{const stock=currentStock(i.id);const status=stock<3?'danger':stock<5?'warn':'safe';return `<div class="row-card master-card"><div class="thumb">${i.image?`<img src="${i.image}" style="width:100%;height:100%;object-fit:cover;border-radius:13px">`:'📦'}</div><div><div class="row-title">${esc(i.name)}</div><div class="row-meta">${esc(i.sku||'-')} · ${esc(i.category)} · 1 ${esc(i.uomBesar)} = ${formatQty(i.konversi)} ${esc(i.uomKecil)}</div><span class="badge ${status}">${status==='safe'?'Aman':status==='warn'?'Menipis':'Kritis'}</span></div><div class="stock-pill"><strong>${formatQty(stock)}</strong><small>${esc(i.uomKecil)}</small><div class="master-actions"><button class="icon-btn" data-edit-item="${i.id}">✏️</button><button class="icon-btn danger" data-delete-item="${i.id}">🗑️</button></div></div></div>`}).join('')||'<div class="list-empty">Belum ada item.</div>';}
function renderWarehouse(){const ins=state.transactions.filter(t=>t.type==='IN').sort((a,b)=>b.at.localeCompare(a.at));const outs=state.transactions.filter(t=>t.type==='OUT').sort((a,b)=>b.at.localeCompare(a.at));$('#inList').innerHTML=ins.map(t=>txHtml(t,'IN')).join('')||'<div class="list-empty">Belum ada transaksi IN.</div>';$('#outList').innerHTML=outs.map(t=>txHtml(t,'OUT')).join('')||'<div class="list-empty">Belum ada transaksi OUT.</div>';
 const bs=[...state.batches].sort((a,b)=>new Date(a.expireDate)-new Date(b.expireDate));$('#batchList').innerHTML=bs.map(b=>{const d=Math.ceil((new Date(b.expireDate)-new Date())/86400000);const cls=d<0?'danger':d<=7?'warn':'safe';return `<div class="row-card"><div class="row-top"><div><div class="row-title">${esc(itemName(b.itemId))}</div><div class="row-meta">Batch ${esc(b.id)} · Expire ${esc(b.expireDate)} · Sisa ${formatQty(b.qty)}</div></div><span class="badge ${cls}">${d<0?'EXPIRED':d+' hari'}</span></div></div>`}).join('')||'<div class="list-empty">Belum ada batch.</div>'}
function txHtml(t,type){return `<div class="row-card"><div class="row-top"><div><div class="row-title">${esc(itemName(t.itemId))}</div><div class="row-meta">${esc(t.note||'-')} · ${formatDateTime(t.at)} · ${esc(t.user)}</div>${t.batchId?`<div class="row-meta">Batch: ${esc(t.batchId)}</div>`:''}</div><div class="stock-pill"><strong style="color:${type==='IN'?'var(--green)':'var(--red)'}">${type==='IN'?'+':'−'}${formatQty(t.qty)}</strong><small>${esc(state.items.find(i=>i.id===t.itemId)?.uomKecil||'UOM')}</small></div></div></div>`}
function renderSO(){const list=state.so.filter(s=>s.date===today()).sort((a,b)=>b.at.localeCompare(a.at));const diffs=list.map(s=>Number(s.physical)-Number(s.system));$('#soCount').textContent=list.length;$('#soDiff').textContent=formatQty(diffs.reduce((a,b)=>a+b,0));const abs=list.reduce((a,s)=>a+Math.abs(Number(s.physical)-Number(s.system)),0);const base=list.reduce((a,s)=>a+Math.max(Number(s.system),1),0);$('#soAccuracy').textContent=(base?Math.max(0,Math.round((1-abs/base)*100)):0)+'%';$('#soList').innerHTML=list.map(s=>{const diff=Number(s.physical)-Number(s.system);const cls=diff===0?'safe':diff>0?'info':'danger';return `<div class="row-card"><div class="row-top"><div><div class="row-title">${esc(itemName(s.itemId))}</div><div class="row-meta">Fisik ${formatQty(s.physical)} · Sistem ${formatQty(s.system)} · ${formatDateTime(s.at)}</div><div class="row-meta">${esc(s.note||'Tidak ada catatan')}</div></div><span class="badge ${cls}">${diff>0?'+':''}${formatQty(diff)}</span></div></div>`}).join('')||'<div class="list-empty">Belum ada SO hari ini.</div>'}
function renderEstimate(){const select=$('#estimateItem');const current=select.value||state.items[0]?.id||'';select.innerHTML=state.items.map(i=>`<option value="${i.id}">${esc(i.name)} · ${esc(i.sku)}</option>`).join('');if(current)select.value=current;calcEstimate();$('#draftList').innerHTML=state.drafts.sort((a,b)=>b.at.localeCompare(a.at)).map(d=>`<div class="row-card"><div class="row-top"><div><div class="row-title">${esc(itemName(d.itemId))}</div><div class="row-meta">Qty rekomendasi ${formatQty(d.qty)} · dibuat ${formatDateTime(d.at)}</div></div><button class="icon-btn danger" data-delete-draft="${d.id}">✕</button></div></div>`).join('')||'<div class="list-empty">Belum ada draft order.</div>'}
function calcEstimate(){const item=state.items.find(i=>i.id===$('#estimateItem')?.value);if(!item)return;const sales=Number($('#estimateSales').value||0),safe=Number($('#estimateSafeDays').value||0),factor=Number($('#estimateFactor').value||1),daily=sales/30,need=daily*safe*factor,rec=Math.max(0,Math.ceil(need-currentStock(item.id)));$('#estimateCurrent').textContent=formatQty(currentStock(item.id));$('#estimateDaily').textContent=formatQty(daily);$('#estimateRecommendation').textContent=formatQty(rec)}
function renderSettings(){const allow=can('manageUsers');$('#addUserBtn').style.display=allow?'block':'none';$('#userMgmtHint').textContent=allow?'Admin dapat mengelola user.':'Hanya Admin.';$('#resetBtn').style.display=can('reset')?'block':'none';$('#exportBtn').style.display=can('export')?'block':'none';$('#importBtn').style.display=can('import')?'block':'none';$('#userList').innerHTML=state.users.map(u=>`<div class="row-card"><div class="row-top"><div><div class="row-title">${esc(u.name)}</div><div class="row-meta">@${esc(u.username)} · ${esc(u.group)}</div></div><span class="badge ${u.active?'safe':'danger'}">${u.active?'Aktif':'Nonaktif'}</span></div></div>`).join('');const pageLabels=['dashboard','master','warehouse','dailyso','estimate','settings'];$('#permissionTable').innerHTML='<div>Group</div>'+pageLabels.map(x=>`<div>${x}</div>`).join('')+Object.keys(GROUPS).map(g=>`<div>${g}</div>`+pageLabels.map(p=>`<div>${GROUPS[g].pages.includes(p)?'✅':'—'}</div>`).join('')).join('')}
function addItemModal(editId){if(!can(editId?'edit':'create'))return showToast('Group ini tidak punya izin mengubah item.');const existing=state.items.find(i=>i.id===editId);const i=existing||{name:'',sku:'',category:'Raw Material',uomBesar:'Karton',uomKecil:'Pcs',konversi:1,opening:0,price:0,displayName:''};const body=`<div class="modal-row"><label>Nama Item<input id="m_name" value="${attr(i.name)}"></label><label>SKU<input id="m_sku" value="${attr(i.sku)}"></label></div><div class="modal-row"><label>Kategori<select id="m_category"><option ${i.category==='Raw Material'?'selected':''}>Raw Material</option><option ${i.category==='Merchandise'?'selected':''}>Merchandise</option><option ${i.category==='Kitchen Supplier'?'selected':''}>Kitchen Supplier</option></select></label><label>Harga Jual<input id="m_price" type="number" value="${Number(i.price||0)}"></label></div><div class="modal-row"><label>UOM Besar<input id="m_ub" value="${attr(i.uomBesar)}"></label><label>UOM Kecil<input id="m_uk" value="${attr(i.uomKecil)}"></label></div><div class="modal-row"><label>Konversi<input id="m_kon" type="number" min="1" value="${Number(i.konversi||1)}"></label><label>Stok Awal<input id="m_open" type="number" min="0" step="0.01" value="${Number(i.opening||0)}" ${existing?'disabled':''}></label></div><label>Nama Display<input id="m_display" value="${attr(i.displayName||i.name)}"></label><div class="hint">Stok awal hanya diatur saat item dibuat.</div>`;openModal(existing?'Edit Item':'Tambah Item',body,existing?'Simpan Perubahan':'Tambah',root=>{const name=root.querySelector('#m_name').value.trim(),sku=root.querySelector('#m_sku').value.trim(),category=root.querySelector('#m_category').value,price=Number(root.querySelector('#m_price').value||0),ub=root.querySelector('#m_ub').value.trim(),uk=root.querySelector('#m_uk').value.trim(),kon=Math.max(1,Number(root.querySelector('#m_kon').value||1)),opening=Math.max(0,Number(root.querySelector('#m_open').value||0)),display=root.querySelector('#m_display').value.trim()||name;if(!name||!ub||!uk)return showToast('Lengkapi field wajib.');if(state.items.some(x=>x.sku===sku&&x.id!==editId))return showToast('SKU sudah digunakan.');if(existing){Object.assign(existing,{name,sku,category,price,uomBesar:ub,uomKecil:uk,konversi:kon,displayName:display});logActivity('ITEM',existing.id,'Item diperbarui: '+name)}else{const ni={id:id(),name,sku:sku||('SKU-'+Math.random().toString(36).slice(2,8).toUpperCase()),category,price,uomBesar:ub,uomKecil:uk,konversi:kon,opening,displayName:display};state.items.push(ni);logActivity('ITEM',ni.id,'Item ditambahkan: '+name)}save();closeModal();renderAll();showToast(existing?'Item diperbarui.':'Item ditambahkan.');});}
function deleteItem(itemId){if(!can('delete'))return showToast('Group ini tidak punya izin hapus item.');const item=state.items.find(i=>i.id===itemId);if(!item)return;if(!confirm(`Hapus ${item.name}? Transaksi tetap tersimpan, tetapi item tidak akan muncul di master.`))return;state.items=state.items.filter(i=>i.id!==itemId);logActivity('ITEM',itemId,'Item dihapus: '+item.name);save();renderAll();}
function transactionModal(type){if(!can('create'))return showToast('Group ini tidak punya izin transaksi.');const title=type==='IN'?'Barang Masuk (IN)':'Barang Keluar (OUT)';const itemOptions=state.items.map(i=>`<option value="${i.id}">${esc(i.name)} · stok ${formatQty(currentStock(i.id))}</option>`).join('');const body=type==='IN'?`<label>Item<select id="m_item">${itemOptions}</select></label><div class="modal-row"><label>Qty<input id="m_qty" type="number" min="0.01" step="0.01"></label><label>Expire Date<input id="m_expire" type="date" value="${today()}"></label></div><label>Catatan<input id="m_note" placeholder="Supplier / keterangan"></label>`:`<label>Item<select id="m_item">${itemOptions}</select></label><label>Batch<select id="m_batch"></select></label><label>Qty<input id="m_qty" type="number" min="0.01" step="0.01"></label><label>Tujuan / Catatan<input id="m_note" placeholder="Bar / Kitchen / lainnya"></label>`;openModal(title,body,'Simpan',root=>{const itemId=root.querySelector('#m_item').value,qty=Number(root.querySelector('#m_qty').value||0),note=root.querySelector('#m_note').value.trim();if(!itemId||qty<=0)return showToast('Qty harus lebih dari 0.');if(type==='IN'){const expire=root.querySelector('#m_expire').value;if(!expire)return showToast('Expire date wajib.');const batch={id:'B-'+Math.random().toString(36).slice(2,7).toUpperCase(),itemId,expireDate:expire,qty,createdAt:new Date().toISOString()};state.batches.push(batch);state.transactions.push({id:id(),at:new Date().toISOString(),type:'IN',itemId,qty,note,user:currentUser.name,batchId:batch.id});logActivity('IN',itemId,`Barang IN ${formatQty(qty)}: ${itemName(itemId)}`)}else{const batchId=root.querySelector('#m_batch').value;const batch=state.batches.find(b=>b.id===batchId);if(!batch)return showToast('Pilih batch.');if(qty>batch.qty)return showToast('Qty melebihi sisa batch.');batch.qty-=qty;state.transactions.push({id:id(),at:new Date().toISOString(),type:'OUT',itemId,qty,note,user:currentUser.name,batchId});logActivity('OUT',itemId,`Barang OUT ${formatQty(qty)}: ${itemName(itemId)}`)}save();closeModal();renderAll();showToast('Transaksi tersimpan.')});const updateBatch=()=>{const itemId=$('#m_item')?.value;const batchSel=$('#m_batch');if(!batchSel)return;const bs=state.batches.filter(b=>b.itemId===itemId&&b.qty>0).sort((a,b)=>new Date(a.expireDate)-new Date(b.expireDate));batchSel.innerHTML=bs.map(b=>`<option value="${b.id}">${b.expireDate} · sisa ${formatQty(b.qty)}</option>`).join('')||'<option value="">Tidak ada batch</option>';};if(type==='OUT'){setTimeout(()=>{updateBatch();$('#m_item').addEventListener('change',updateBatch)},0)}}
function soModal(){if(!can('create'))return showToast('Group ini tidak punya izin input SO.');const opts=state.items.map(i=>`<option value="${i.id}">${esc(i.name)}</option>`).join('');const body=`<label>Tanggal<input id="m_date" type="date" value="${today()}"></label><label>Item<select id="m_item">${opts}</select></label><div class="modal-row"><label>Stok Fisik<input id="m_phys" type="number" min="0" step="0.01"></label><label>Stok Sistem<input id="m_sys" readonly></label></div><label>Catatan<input id="m_note" placeholder="Kondisi / keterangan"></label>`;openModal('Daily Stock Opname',body,'Simpan SO',root=>{const itemId=root.querySelector('#m_item').value,date=root.querySelector('#m_date').value,physical=Number(root.querySelector('#m_phys').value),system=currentStock(itemId),note=root.querySelector('#m_note').value.trim();if(!itemId||!date||Number.isNaN(physical))return showToast('Lengkapi data SO.');const record={id:id(),date,itemId,physical,system,note,at:new Date().toISOString(),user:currentUser.name};state.so.push(record);logActivity('SO',itemId,`SO ${itemName(itemId)} selisih ${formatQty(physical-system)}`);save();closeModal();renderAll();showToast('SO tersimpan.')});setTimeout(()=>{const update=()=>{$('#m_sys').value=formatQty(currentStock($('#m_item').value))};update();$('#m_item').addEventListener('change',update)},0)}
function addDraft(){if(!can('create'))return showToast('Group ini tidak punya izin membuat draft.');const itemId=$('#estimateItem').value;const qty=Number($('#estimateRecommendation').textContent.replace(/\./g,'').replace(',','.'));if(!itemId)return;if(qty<=0)return showToast('Rekomendasi order 0.');state.drafts.push({id:id(),itemId,qty,at:new Date().toISOString(),user:currentUser.name});save();renderEstimate();showToast('Masuk ke draft order.')}
function addUserModal(){if(!can('manageUsers'))return;const body=`<div class="modal-row"><label>Nama<input id="m_name"></label><label>Username<input id="m_username"></label></div><div class="modal-row"><label>Password<input id="m_password" type="password"></label><label>Group<select id="m_group">${Object.keys(GROUPS).map(g=>`<option>${g}</option>`).join('')}</select></label></div><label class="check-row"><input id="m_active" type="checkbox" checked> User aktif</label>`;openModal('Tambah User',body,'Simpan',root=>{const name=root.querySelector('#m_name').value.trim(),username=root.querySelector('#m_username').value.trim(),password=root.querySelector('#m_password').value,group=root.querySelector('#m_group').value,active=root.querySelector('#m_active').checked;if(!name||!username||!password)return showToast('Lengkapi data user.');if(state.users.some(u=>u.username.toLowerCase()===username.toLowerCase()))return showToast('Username sudah ada.');state.users.push({id:id(),name,username,password,group,active});save();closeModal();renderSettings();showToast('User ditambahkan.')})}
function exportData(){if(!can('export'))return;const blob=new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='inventory-kk-backup-'+today()+'.json';a.click();URL.revokeObjectURL(a.href)}
function importData(file){if(!can('import'))return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(!Array.isArray(d.items)||!Array.isArray(d.transactions)||!Array.isArray(d.batches))throw new Error('Format backup tidak cocok');state={users:Array.isArray(d.users)?d.users:state.users,items:d.items,transactions:d.transactions,batches:d.batches,so:Array.isArray(d.so)?d.so:[],drafts:Array.isArray(d.drafts)?d.drafts:[],activity:Array.isArray(d.activity)?d.activity:[]};save();renderAll();showToast('Backup berhasil diimport.')}catch(e){showToast('File backup tidak valid.')}};r.readAsText(file)}
function resetData(){if(!can('reset'))return;if(!confirm('Reset semua data inventory ke demo awal?'))return;state={users:DEFAULT_USERS,items:seedItems,transactions:[],batches:[],so:[],drafts:[],activity:[]};save();renderAll();showToast('Data direset ke demo awal.')}
function esc(s){return String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}function attr(s){return esc(s)}

document.addEventListener('DOMContentLoaded',()=>{load();restoreSession();
 $('#loginForm').addEventListener('submit',e=>{e.preventDefault();login($('#loginUsername').value.trim(),$('#loginPassword').value)});
 $('#menuLogout').onclick=logout;$('#userMenuBtn').onclick=()=>$('#userMenu').classList.toggle('hidden');document.addEventListener('click',e=>{if(!e.target.closest('#userMenu')&&!e.target.closest('#userMenuBtn'))closeUserMenu()});
 $('#bottomNav').addEventListener('click',e=>{const b=e.target.closest('.nav-btn');if(b)showPage(b.dataset.page)});document.body.addEventListener('click',e=>{const go=e.target.closest('[data-go]');if(go)showPage(go.dataset.go);const edit=e.target.closest('[data-edit-item]');if(edit)addItemModal(edit.dataset.editItem);const del=e.target.closest('[data-delete-item]');if(del)deleteItem(del.dataset.deleteItem);const dd=e.target.closest('[data-delete-draft]');if(dd){state.drafts=state.drafts.filter(d=>d.id!==dd.dataset.deleteDraft);save();renderEstimate();showToast('Draft dihapus.')}});
 $('#addItemBtn').onclick=()=>addItemModal();$('#openInBtn').onclick=()=>transactionModal('IN');$('#openOutBtn').onclick=()=>transactionModal('OUT');$('#openSoBtn').onclick=soModal;$('#addDraftBtn').onclick=addDraft;$('#addUserBtn').onclick=addUserModal;$('#exportBtn').onclick=exportData;$('#importBtn').onclick=()=>$('#importFile').click();$('#importFile').onchange=e=>{if(e.target.files[0])importData(e.target.files[0]);e.target.value=''};$('#resetBtn').onclick=resetData;
 $('#masterSearch').addEventListener('input',renderMaster);$('#masterCategory').addEventListener('change',renderMaster);$('#estimateItem').addEventListener('change',calcEstimate);['estimateSales','estimateSafeDays','estimateFactor'].forEach(id=>$('#'+id).addEventListener('input',calcEstimate));
 $$('.tab').forEach(t=>t.addEventListener('click',()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.tab-panel').forEach(x=>x.classList.remove('active'));t.classList.add('active');$('#warehouse-'+t.dataset.tab).classList.add('active')}));
});
